[I 2024-04-06 09:07:32.479 ServerApp] Package jupyterlab took 0.0000s to import
[I 2024-04-06 09:07:32.598 ServerApp] Package jupyter_lsp took 0.1181s to import
[W 2024-04-06 09:07:32.598 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-04-06 09:07:32.664 ServerApp] Package jupyter_server_terminals took 0.0653s to import
[I 2024-04-06 09:07:33.378 ServerApp] Package jupytext took 0.7133s to import
[I 2024-04-06 09:07:33.379 ServerApp] Package notebook_shim took 0.0000s to import
[W 2024-04-06 09:07:33.379 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-04-06 09:07:33.409 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-04-06 09:07:33.422 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-04-06 09:07:33.438 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-04-06 09:07:33.439 ServerApp] jupytext | extension was successfully linked.
[I 2024-04-06 09:07:34.774 ServerApp] Package jupyter_nbextensions_configurator took 1.0134s to import
[W 2024-04-06 09:07:34.774 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_nbextensions_configurator. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-04-06 09:07:34.774 ServerApp] jupyter_nbextensions_configurator | extension was found and enabled by notebook_shim. Consider moving the extension to Jupyter Server's extension paths.
[I 2024-04-06 09:07:34.774 ServerApp] jupyter_nbextensions_configurator | extension was successfully linked.
[I 2024-04-06 09:07:34.774 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-04-06 09:07:34.933 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-04-06 09:07:34.941 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-04-06 09:07:34.942 ServerApp] [jupyter_nbextensions_configurator] enabled 0.6.3
[I 2024-04-06 09:07:34.942 ServerApp] jupyter_nbextensions_configurator | extension was successfully loaded.
[I 2024-04-06 09:07:34.944 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-04-06 09:07:34.949 LabApp] JupyterLab extension loaded from /home/hass/base/lib/python3.11/site-packages/jupyterlab
[I 2024-04-06 09:07:34.949 LabApp] JupyterLab application directory is /home/hass/base/share/jupyter/lab
[I 2024-04-06 09:07:34.950 LabApp] Extension Manager is 'pypi'.
[I 2024-04-06 09:07:34.958 ServerApp] jupyterlab | extension was successfully loaded.
[W 2024-04-06 09:07:34.958 ServerApp] [Jupytext Server Extension] Async contents managers like AsyncLargeFileManager are not supported at the moment (https://github.com/mwouts/jupytext/issues/1020). We will derive a contents manager from LargeFileManager instead.
[I 2024-04-06 09:07:34.958 ServerApp] [Jupytext Server Extension] Deriving a JupytextContentsManager from LargeFileManager
[I 2024-04-06 09:07:34.961 ServerApp] jupytext | extension was successfully loaded.
[I 2024-04-06 09:07:34.963 ServerApp] Serving notebooks from local directory: /home/hass/Documents/webdev/dev2
[I 2024-04-06 09:07:34.963 ServerApp] Jupyter Server 2.10.1 is running at:
[I 2024-04-06 09:07:34.963 ServerApp] http://localhost:8888/lab
[I 2024-04-06 09:07:34.963 ServerApp]     http://127.0.0.1:8888/lab
[I 2024-04-06 09:07:34.963 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2024-04-06 09:07:36.090 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[W 2024-04-06 09:07:43.204 ServerApp] 404 GET /api/contents/Untitled1.ipynb?content=0&1712390863192 (bccbc04e7c1d42f299202d7a3f8129a7@127.0.0.1) 0.99ms referer=http://localhost:8888/lab/tree/Untitled1.ipynb
[W 2024-04-06 09:07:43.204 ServerApp] 404 GET /api/contents/Untitled1.ipynb?content=0&1712390863192 (127.0.0.1): file or directory does not exist: 'Untitled1.ipynb'
[W 2024-04-06 09:07:43.207 ServerApp] 404 GET /api/contents/img/icons/Untitled.ipynb?content=0&1712390863192 (bccbc04e7c1d42f299202d7a3f8129a7@127.0.0.1) 0.89ms referer=http://localhost:8888/lab/tree/Untitled1.ipynb
[W 2024-04-06 09:07:43.207 ServerApp] 404 GET /api/contents/img/icons/Untitled.ipynb?content=0&1712390863192 (127.0.0.1): file or directory does not exist: 'img/icons/Untitled.ipynb'
[W 2024-04-06 09:07:43.353 ServerApp] 404 GET /api/contents/Untitled.ipynb?content=0&1712390863191 (bccbc04e7c1d42f299202d7a3f8129a7@127.0.0.1) 0.87ms referer=http://localhost:8888/lab/tree/Untitled1.ipynb
[W 2024-04-06 09:07:43.353 ServerApp] 404 GET /api/contents/Untitled.ipynb?content=0&1712390863191 (127.0.0.1): file or directory does not exist: 'Untitled.ipynb'
[I 2024-04-06 09:07:43.468 LabApp] Build is up to date
[W 2024-04-06 09:07:44.597 ServerApp] 404 GET /api/contents/Untitled1.ipynb?content=0&1712390864593 (bccbc04e7c1d42f299202d7a3f8129a7@127.0.0.1) 0.97ms referer=http://localhost:8888/lab/tree/Untitled1.ipynb
[W 2024-04-06 09:07:44.598 ServerApp] 404 GET /api/contents/Untitled1.ipynb?content=0&1712390864593 (127.0.0.1): file or directory does not exist: 'Untitled1.ipynb'
[W 2024-04-06 12:18:00.467 ServerApp] 404 GET /hub/api (@127.0.0.1) 154.87ms referer=None
[W 2024-04-06 12:18:00.479 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.27ms referer=None
[W 2024-04-06 12:18:00.480 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.11ms referer=None
[W 2024-04-06 12:18:00.481 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.75ms referer=None
[W 2024-04-06 12:18:00.580 ServerApp] 404 GET /tree? (@127.0.0.1) 1.04ms referer=None
[W 2024-04-06 12:18:00.843 ServerApp] 404 GET /tree? (@127.0.0.1) 1.13ms referer=None
[W 2024-04-06 12:18:00.859 ServerApp] 404 GET /tree? (@127.0.0.1) 1.10ms referer=None
[W 2024-04-06 12:18:00.861 ServerApp] 404 GET /tree? (@127.0.0.1) 0.84ms referer=None
[W 2024-04-06 12:18:01.596 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-06 12:18:01.795 ServerApp] 403 GET /api/kernelspecs?1712402280957 (@127.0.0.1) 199.22ms referer=None
[W 2024-04-06 12:18:01.796 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-06 12:18:01.796 ServerApp] 403 GET /api/kernels?1712402280967 (@127.0.0.1) 1.45ms referer=None
[W 2024-04-06 12:18:01.797 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-06 12:18:01.797 ServerApp] 403 GET /api/kernelspecs?1712402280973 (@127.0.0.1) 2.12ms referer=None
[W 2024-04-06 12:18:01.798 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-06 12:18:01.799 ServerApp] 403 GET /api/kernels?1712402280974 (@127.0.0.1) 1.35ms referer=None
[W 2024-04-06 12:18:01.799 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-06 12:18:01.800 ServerApp] 403 GET /api/kernels?1712402280975 (@127.0.0.1) 1.96ms referer=None
[W 2024-04-06 12:18:01.801 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-06 12:18:01.801 ServerApp] 403 GET /api/sessions?1712402280977 (@127.0.0.1) 1.56ms referer=None
[W 2024-04-06 12:18:01.802 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-06 12:18:01.802 ServerApp] 403 GET /api/kernels?1712402280983 (@127.0.0.1) 2.25ms referer=None
[W 2024-04-06 12:18:01.802 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-06 12:18:01.803 ServerApp] 403 GET /api/sessions?1712402280985 (@127.0.0.1) 2.88ms referer=None
[W 2024-04-06 12:18:01.814 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-06 12:18:01.815 ServerApp] 403 GET /api/kernelspecs?1712402281693 (@127.0.0.1) 1.33ms referer=None
[W 2024-04-06 12:18:01.816 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-06 12:18:01.816 ServerApp] 403 GET /api/kernels?1712402281695 (@127.0.0.1) 1.00ms referer=None
[W 2024-04-06 12:18:01.905 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-06 12:18:01.906 ServerApp] 403 GET /api/kernels?1712402281814 (@127.0.0.1) 1.15ms referer=None
[W 2024-04-06 12:18:01.907 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-06 12:18:01.907 ServerApp] 403 GET /api/sessions?1712402281818 (@127.0.0.1) 0.87ms referer=None
[W 2024-04-06 12:18:01.912 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-06 12:18:01.913 ServerApp] 403 GET /api/kernelspecs?1712402281905 (@127.0.0.1) 1.27ms referer=None
[I 2024-04-06 12:18:05.950 ServerApp] User 53fbc83d543b41058794970421bbab0e logged in.
[I 2024-04-06 12:18:05.950 ServerApp] 302 POST /login? (53fbc83d543b41058794970421bbab0e@127.0.0.1) 321.94ms
[W 2024-04-11 14:33:20.125 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.13ms referer=None
[W 2024-04-11 14:33:20.158 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.10ms referer=None
[W 2024-04-11 14:33:20.160 ServerApp] 404 GET /hub/api (@127.0.0.1) 0.95ms referer=None
[W 2024-04-11 14:33:20.160 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.47ms referer=None
[W 2024-04-11 14:33:20.194 ServerApp] 404 GET /tree? (@127.0.0.1) 1.10ms referer=None
[W 2024-04-11 14:33:20.290 ServerApp] 404 GET /tree? (@127.0.0.1) 0.97ms referer=None
[W 2024-04-11 14:33:20.292 ServerApp] 404 GET /tree? (@127.0.0.1) 0.75ms referer=None
[W 2024-04-11 14:33:20.293 ServerApp] 404 GET /tree? (@127.0.0.1) 0.79ms referer=None
[W 2024-04-11 14:33:20.504 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-11 14:33:20.504 ServerApp] 403 GET /api/kernelspecs?1712842400300 (@127.0.0.1) 1.17ms referer=None
[W 2024-04-11 14:33:20.506 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-11 14:33:20.507 ServerApp] 403 GET /api/kernels?1712842400305 (@127.0.0.1) 1.01ms referer=None
[W 2024-04-11 14:33:20.507 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-11 14:33:20.508 ServerApp] 403 GET /api/kernelspecs?1712842400311 (@127.0.0.1) 1.03ms referer=None
[W 2024-04-11 14:33:20.508 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-11 14:33:20.509 ServerApp] 403 GET /api/kernels?1712842400313 (@127.0.0.1) 1.00ms referer=None
[W 2024-04-11 14:33:20.510 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-11 14:33:20.511 ServerApp] 403 GET /api/kernels?1712842400319 (@127.0.0.1) 1.54ms referer=None
[W 2024-04-11 14:33:20.511 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-11 14:33:20.511 ServerApp] 403 GET /api/sessions?1712842400321 (@127.0.0.1) 2.14ms referer=None
[W 2024-04-11 14:33:20.512 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-11 14:33:20.512 ServerApp] 403 GET /api/kernels?1712842400323 (@127.0.0.1) 2.75ms referer=None
[W 2024-04-11 14:33:20.513 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-11 14:33:20.513 ServerApp] 403 GET /api/sessions?1712842400324 (@127.0.0.1) 3.69ms referer=None
[W 2024-04-11 14:33:21.174 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-11 14:33:21.175 ServerApp] 403 GET /api/kernelspecs?1712842401091 (@127.0.0.1) 1.15ms referer=None
[W 2024-04-11 14:33:21.175 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-11 14:33:21.176 ServerApp] 403 GET /api/kernels?1712842401092 (@127.0.0.1) 1.01ms referer=None
[W 2024-04-11 14:33:21.461 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-11 14:33:21.462 ServerApp] 403 GET /api/kernels?1712842401178 (@127.0.0.1) 1.12ms referer=None
[W 2024-04-11 14:33:21.463 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-11 14:33:21.463 ServerApp] 403 GET /api/sessions?1712842401179 (@127.0.0.1) 0.96ms referer=None
[W 2024-04-11 14:33:21.584 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-11 14:33:21.585 ServerApp] 403 GET /api/kernelspecs?1712842401464 (@127.0.0.1) 1.14ms referer=None
[I 2024-04-11 14:33:24.314 ServerApp] User d24849ad4de04d14a6d904af2361fc92 logged in.
[I 2024-04-11 14:33:24.315 ServerApp] 302 POST /login? (d24849ad4de04d14a6d904af2361fc92@127.0.0.1) 251.93ms
[W 2024-04-17 10:45:57.768 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.23ms referer=None
[W 2024-04-17 10:45:57.777 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.25ms referer=None
[W 2024-04-17 10:45:57.778 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.05ms referer=None
[W 2024-04-17 10:45:57.779 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.52ms referer=None
[W 2024-04-17 10:45:57.883 ServerApp] 404 GET /tree? (@127.0.0.1) 1.05ms referer=None
[W 2024-04-17 10:45:58.891 ServerApp] 404 GET /tree? (@127.0.0.1) 1.04ms referer=None
[W 2024-04-17 10:45:58.892 ServerApp] 404 GET /tree? (@127.0.0.1) 0.97ms referer=None
[W 2024-04-17 10:45:58.893 ServerApp] 404 GET /tree? (@127.0.0.1) 1.48ms referer=None
[W 2024-04-17 10:45:58.996 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:58.997 ServerApp] 403 GET /api/kernelspecs?1713347158942 (@127.0.0.1) 0.95ms referer=None
[W 2024-04-17 10:45:58.997 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:58.998 ServerApp] 403 GET /api/kernels?1713347158946 (@127.0.0.1) 0.72ms referer=None
[W 2024-04-17 10:45:58.998 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:58.999 ServerApp] 403 GET /api/kernelspecs?1713347158951 (@127.0.0.1) 0.91ms referer=None
[W 2024-04-17 10:45:58.999 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.000 ServerApp] 403 GET /api/kernels?1713347158953 (@127.0.0.1) 0.95ms referer=None
[W 2024-04-17 10:45:59.002 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.002 ServerApp] 403 GET /api/kernels?1713347158955 (@127.0.0.1) 2.28ms referer=None
[W 2024-04-17 10:45:59.002 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.003 ServerApp] 403 GET /api/sessions?1713347158958 (@127.0.0.1) 2.89ms referer=None
[W 2024-04-17 10:45:59.003 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.004 ServerApp] 403 GET /api/kernels?1713347158961 (@127.0.0.1) 3.50ms referer=None
[W 2024-04-17 10:45:59.004 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.005 ServerApp] 403 GET /api/sessions?1713347158962 (@127.0.0.1) 4.07ms referer=None
[W 2024-04-17 10:45:59.005 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.005 ServerApp] 403 GET /api/kernelspecs?1713347158984 (@127.0.0.1) 4.61ms referer=None
[W 2024-04-17 10:45:59.006 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.006 ServerApp] 403 GET /api/kernels?1713347158986 (@127.0.0.1) 5.14ms referer=None
[W 2024-04-17 10:45:59.022 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.022 ServerApp] 403 GET /api/kernels?1713347158997 (@127.0.0.1) 1.07ms referer=None
[W 2024-04-17 10:45:59.023 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.023 ServerApp] 403 GET /api/sessions?1713347158998 (@127.0.0.1) 0.76ms referer=None
[W 2024-04-17 10:45:59.103 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.104 ServerApp] 403 GET /api/kernelspecs?1713347159021 (@127.0.0.1) 1.17ms referer=None
[W 2024-04-17 10:45:59.104 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.105 ServerApp] 403 GET /api/kernelspecs?1713347159022 (@127.0.0.1) 1.04ms referer=None
[W 2024-04-17 10:45:59.106 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.82ms referer=None
[W 2024-04-17 10:45:59.113 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.04ms referer=None
[W 2024-04-17 10:45:59.114 ServerApp] 404 GET /hub/api (@127.0.0.1) 0.67ms referer=None
[W 2024-04-17 10:45:59.138 ServerApp] 404 GET /tree? (@127.0.0.1) 1.08ms referer=None
[W 2024-04-17 10:45:59.142 ServerApp] 404 GET /tree? (@127.0.0.1) 1.03ms referer=None
[W 2024-04-17 10:45:59.143 ServerApp] 404 GET /tree? (@127.0.0.1) 0.82ms referer=None
[W 2024-04-17 10:45:59.274 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.275 ServerApp] 403 GET /api/kernelspecs?1713347159247 (@127.0.0.1) 1.50ms referer=None
[W 2024-04-17 10:45:59.275 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.276 ServerApp] 403 GET /api/kernels?1713347159248 (@127.0.0.1) 1.97ms referer=None
[W 2024-04-17 10:45:59.276 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.276 ServerApp] 403 GET /api/kernelspecs?1713347159250 (@127.0.0.1) 2.53ms referer=None
[W 2024-04-17 10:45:59.276 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.277 ServerApp] 403 GET /api/kernels?1713347159251 (@127.0.0.1) 3.01ms referer=None
[W 2024-04-17 10:45:59.278 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.279 ServerApp] 403 GET /api/kernels?1713347159258 (@127.0.0.1) 1.61ms referer=None
[W 2024-04-17 10:45:59.279 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.279 ServerApp] 403 GET /api/sessions?1713347159259 (@127.0.0.1) 2.06ms referer=None
[W 2024-04-17 10:45:59.279 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.280 ServerApp] 403 GET /api/kernels?1713347159260 (@127.0.0.1) 2.51ms referer=None
[W 2024-04-17 10:45:59.280 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.280 ServerApp] 403 GET /api/sessions?1713347159261 (@127.0.0.1) 2.98ms referer=None
[W 2024-04-17 10:45:59.281 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.281 ServerApp] 403 GET /api/kernelspecs?1713347159263 (@127.0.0.1) 3.43ms referer=None
[W 2024-04-17 10:45:59.281 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.282 ServerApp] 403 GET /api/kernels?1713347159263 (@127.0.0.1) 4.08ms referer=None
[W 2024-04-17 10:45:59.283 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.284 ServerApp] 403 GET /api/kernels?1713347159266 (@127.0.0.1) 1.22ms referer=None
[W 2024-04-17 10:45:59.284 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.285 ServerApp] 403 GET /api/sessions?1713347159267 (@127.0.0.1) 1.85ms referer=None
[W 2024-04-17 10:45:59.298 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.10ms referer=None
[W 2024-04-17 10:45:59.303 ServerApp] 404 GET /tree? (@127.0.0.1) 0.84ms referer=None
[W 2024-04-17 10:45:59.313 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.314 ServerApp] 403 GET /api/kernelspecs?1713347159310 (@127.0.0.1) 1.47ms referer=None
[W 2024-04-17 10:45:59.314 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.315 ServerApp] 403 GET /api/kernels?1713347159311 (@127.0.0.1) 1.84ms referer=None
[W 2024-04-17 10:45:59.318 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.319 ServerApp] 403 GET /api/kernels?1713347159312 (@127.0.0.1) 1.13ms referer=None
[W 2024-04-17 10:45:59.319 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.320 ServerApp] 403 GET /api/sessions?1713347159313 (@127.0.0.1) 1.25ms referer=None
[W 2024-04-17 10:45:59.321 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:45:59.321 ServerApp] 403 GET /api/kernelspecs?1713347159317 (@127.0.0.1) 1.01ms referer=None
[I 2024-04-17 10:46:01.397 ServerApp] User c31154c80d814de581fe4ef638973c1e logged in.
[I 2024-04-17 10:46:01.397 ServerApp] 302 POST /login? (c31154c80d814de581fe4ef638973c1e@127.0.0.1) 199.38ms
[W 2024-04-17 10:46:21.205 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.08ms referer=None
[W 2024-04-17 10:46:21.207 ServerApp] 404 GET /hub/api (@127.0.0.1) 0.82ms referer=None
[W 2024-04-17 10:46:21.252 ServerApp] 404 GET /hub/api (@127.0.0.1) 0.99ms referer=None
[W 2024-04-17 10:46:21.285 ServerApp] 404 GET /tree? (@127.0.0.1) 0.99ms referer=None
[W 2024-04-17 10:46:21.452 ServerApp] 404 GET /tree? (@127.0.0.1) 1.06ms referer=None
[W 2024-04-17 10:46:21.453 ServerApp] 404 GET /hub/api (@127.0.0.1) 0.93ms referer=None
[W 2024-04-17 10:46:21.542 ServerApp] 404 GET /tree? (@127.0.0.1) 1.04ms referer=None
[W 2024-04-17 10:46:21.608 ServerApp] 404 GET /tree? (@127.0.0.1) 1.05ms referer=None
[W 2024-04-17 10:46:21.800 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:21.801 ServerApp] 403 GET /api/kernelspecs?1713347181597 (@127.0.0.1) 1.10ms referer=None
[W 2024-04-17 10:46:21.816 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:21.816 ServerApp] 403 GET /api/kernels?1713347181599 (@127.0.0.1) 1.17ms referer=None
[W 2024-04-17 10:46:21.817 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:21.818 ServerApp] 403 GET /api/kernels?1713347181601 (@127.0.0.1) 0.91ms referer=None
[W 2024-04-17 10:46:21.826 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:21.827 ServerApp] 403 GET /api/sessions?1713347181602 (@127.0.0.1) 1.10ms referer=None
[W 2024-04-17 10:46:21.828 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:21.828 ServerApp] 403 GET /api/kernelspecs?1713347181613 (@127.0.0.1) 0.90ms referer=None
[W 2024-04-17 10:46:21.829 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:21.830 ServerApp] 403 GET /api/kernels?1713347181614 (@127.0.0.1) 0.94ms referer=None
[W 2024-04-17 10:46:21.831 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:21.831 ServerApp] 403 GET /api/kernels?1713347181616 (@127.0.0.1) 0.91ms referer=None
[W 2024-04-17 10:46:21.832 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:21.833 ServerApp] 403 GET /api/sessions?1713347181618 (@127.0.0.1) 0.88ms referer=None
[W 2024-04-17 10:46:21.834 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:21.834 ServerApp] 403 GET /api/kernelspecs?1713347181803 (@127.0.0.1) 0.83ms referer=None
[W 2024-04-17 10:46:21.835 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:21.835 ServerApp] 403 GET /api/kernels?1713347181804 (@127.0.0.1) 0.88ms referer=None
[W 2024-04-17 10:46:21.865 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:21.865 ServerApp] 403 GET /api/kernels?1713347181837 (@127.0.0.1) 1.31ms referer=None
[W 2024-04-17 10:46:21.872 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:21.872 ServerApp] 403 GET /api/sessions?1713347181843 (@127.0.0.1) 1.13ms referer=None
[W 2024-04-17 10:46:21.898 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:21.898 ServerApp] 403 GET /api/kernelspecs?1713347181872 (@127.0.0.1) 1.26ms referer=None
[W 2024-04-17 10:46:21.900 ServerApp] 404 GET /hub/api (@127.0.0.1) 0.94ms referer=None
[W 2024-04-17 10:46:21.905 ServerApp] 404 GET /tree? (@127.0.0.1) 1.08ms referer=None
[W 2024-04-17 10:46:22.390 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:22.391 ServerApp] 403 GET /api/kernelspecs?1713347181844 (@127.0.0.1) 1.14ms referer=None
[W 2024-04-17 10:46:22.392 ServerApp] 404 GET /hub/api (@127.0.0.1) 0.94ms referer=None
[W 2024-04-17 10:46:22.393 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.41ms referer=None
[W 2024-04-17 10:46:22.758 ServerApp] 404 GET /tree? (@127.0.0.1) 1.04ms referer=None
[W 2024-04-17 10:46:22.759 ServerApp] 404 GET /tree? (@127.0.0.1) 0.78ms referer=None
[W 2024-04-17 10:46:22.760 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:22.760 ServerApp] 403 GET /api/kernelspecs?1713347182443 (@127.0.0.1) 0.91ms referer=None
[W 2024-04-17 10:46:22.761 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:22.762 ServerApp] 403 GET /api/kernels?1713347182445 (@127.0.0.1) 0.89ms referer=None
[W 2024-04-17 10:46:22.763 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:22.763 ServerApp] 403 GET /api/kernels?1713347182450 (@127.0.0.1) 0.85ms referer=None
[W 2024-04-17 10:46:22.764 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:22.765 ServerApp] 403 GET /api/sessions?1713347182451 (@127.0.0.1) 0.91ms referer=None
[W 2024-04-17 10:46:22.937 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:22.937 ServerApp] 403 GET /api/kernelspecs?1713347182846 (@127.0.0.1) 1.14ms referer=None
[W 2024-04-17 10:46:22.943 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:22.944 ServerApp] 403 GET /api/kernels?1713347182847 (@127.0.0.1) 1.12ms referer=None
[W 2024-04-17 10:46:22.945 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:22.946 ServerApp] 403 GET /api/kernelspecs?1713347182849 (@127.0.0.1) 1.00ms referer=None
[W 2024-04-17 10:46:22.947 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:22.947 ServerApp] 403 GET /api/kernels?1713347182850 (@127.0.0.1) 0.92ms referer=None
[W 2024-04-17 10:46:22.949 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.09ms referer=None
[W 2024-04-17 10:46:22.950 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:22.951 ServerApp] 403 GET /api/kernels?1713347182858 (@127.0.0.1) 0.91ms referer=None
[W 2024-04-17 10:46:22.952 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:22.952 ServerApp] 403 GET /api/sessions?1713347182859 (@127.0.0.1) 0.85ms referer=None
[W 2024-04-17 10:46:22.953 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:22.954 ServerApp] 403 GET /api/kernels?1713347182860 (@127.0.0.1) 0.88ms referer=None
[W 2024-04-17 10:46:22.955 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:22.955 ServerApp] 403 GET /api/sessions?1713347182860 (@127.0.0.1) 0.88ms referer=None
[W 2024-04-17 10:46:23.042 ServerApp] 404 GET /tree? (@127.0.0.1) 1.02ms referer=None
[W 2024-04-17 10:46:23.110 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:23.110 ServerApp] 403 GET /api/kernelspecs?1713347183103 (@127.0.0.1) 1.15ms referer=None
[W 2024-04-17 10:46:23.111 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:23.112 ServerApp] 403 GET /api/kernels?1713347183106 (@127.0.0.1) 1.00ms referer=None
[W 2024-04-17 10:46:23.176 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:23.177 ServerApp] 403 GET /api/kernels?1713347183109 (@127.0.0.1) 1.19ms referer=None
[W 2024-04-17 10:46:23.178 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:23.178 ServerApp] 403 GET /api/sessions?1713347183110 (@127.0.0.1) 0.93ms referer=None
[W 2024-04-17 10:46:23.278 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-17 10:46:23.279 ServerApp] 403 GET /api/kernelspecs?1713347183176 (@127.0.0.1) 1.16ms referer=None
[I 2024-04-17 10:46:33.895 ServerApp] User 374c8c43719e42e29d564e6b0ac71efb logged in.
[I 2024-04-17 10:46:33.896 ServerApp] 302 POST /login? (374c8c43719e42e29d564e6b0ac71efb@127.0.0.1) 159.64ms
[I 2024-04-18 09:50:39.419 LabApp] Build is up to date
[W 2024-04-18 09:50:42.980 ServerApp] 404 GET /api/contents/Untitled1.ipynb?content=0&1713430242975 (bccbc04e7c1d42f299202d7a3f8129a7@127.0.0.1) 1.36ms referer=http://localhost:8888/lab/tree/Untitled1.ipynb
[W 2024-04-18 09:50:42.980 ServerApp] 404 GET /api/contents/Untitled1.ipynb?content=0&1713430242975 (127.0.0.1): file or directory does not exist: 'Untitled1.ipynb'
[W 2024-04-20 12:25:05.332 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.54ms referer=None
[W 2024-04-20 12:25:05.333 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.23ms referer=None
[W 2024-04-20 12:25:05.363 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.04ms referer=None
[W 2024-04-20 12:25:05.364 ServerApp] 404 GET /hub/api (@127.0.0.1) 0.80ms referer=None
[W 2024-04-20 12:25:05.400 ServerApp] 404 GET /tree? (@127.0.0.1) 1.07ms referer=None
[W 2024-04-20 12:25:05.434 ServerApp] 404 GET /tree? (@127.0.0.1) 1.59ms referer=None
[W 2024-04-20 12:25:05.530 ServerApp] 404 GET /tree? (@127.0.0.1) 1.08ms referer=None
[W 2024-04-20 12:25:05.533 ServerApp] 404 GET /tree? (@127.0.0.1) 0.99ms referer=None
[W 2024-04-20 12:25:05.827 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:05.835 ServerApp] 403 GET /api/kernelspecs?1713612305797 (@127.0.0.1) 9.58ms referer=None
[W 2024-04-20 12:25:05.837 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:05.839 ServerApp] 403 GET /api/kernels?1713612305798 (@127.0.0.1) 3.47ms referer=None
[W 2024-04-20 12:25:05.843 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:05.845 ServerApp] 403 GET /api/kernels?1713612305825 (@127.0.0.1) 4.32ms referer=None
[W 2024-04-20 12:25:05.846 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:05.847 ServerApp] 403 GET /api/sessions?1713612305828 (@127.0.0.1) 5.86ms referer=None
[W 2024-04-20 12:25:05.852 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:05.853 ServerApp] 403 GET /api/kernelspecs?1713612305785 (@127.0.0.1) 5.36ms referer=None
[W 2024-04-20 12:25:05.854 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:05.855 ServerApp] 403 GET /api/kernels?1713612305787 (@127.0.0.1) 6.65ms referer=None
[W 2024-04-20 12:25:05.856 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:05.857 ServerApp] 403 GET /api/kernelspecs?1713612305789 (@127.0.0.1) 8.06ms referer=None
[W 2024-04-20 12:25:05.857 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:05.859 ServerApp] 403 GET /api/kernels?1713612305790 (@127.0.0.1) 10.11ms referer=None
[W 2024-04-20 12:25:05.860 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:05.862 ServerApp] 403 GET /api/kernels?1713612305791 (@127.0.0.1) 12.09ms referer=None
[W 2024-04-20 12:25:05.863 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:05.865 ServerApp] 403 GET /api/sessions?1713612305792 (@127.0.0.1) 14.73ms referer=None
[W 2024-04-20 12:25:05.866 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:05.868 ServerApp] 403 GET /api/kernels?1713612305793 (@127.0.0.1) 17.05ms referer=None
[W 2024-04-20 12:25:05.869 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:05.870 ServerApp] 403 GET /api/sessions?1713612305794 (@127.0.0.1) 19.39ms referer=None
[W 2024-04-20 12:25:05.875 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:05.877 ServerApp] 403 GET /api/kernelspecs?1713612305845 (@127.0.0.1) 4.55ms referer=None
[W 2024-04-20 12:25:05.902 ServerApp] 404 GET /hub/api (@127.0.0.1) 0.92ms referer=None
[W 2024-04-20 12:25:05.922 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.14ms referer=None
[W 2024-04-20 12:25:05.924 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.02ms referer=None
[W 2024-04-20 12:25:05.924 ServerApp] 404 GET /tree? (@127.0.0.1) 1.50ms referer=None
[W 2024-04-20 12:25:05.972 ServerApp] 404 GET /tree? (@127.0.0.1) 0.83ms referer=None
[W 2024-04-20 12:25:05.978 ServerApp] 404 GET /tree? (@127.0.0.1) 1.05ms referer=None
[W 2024-04-20 12:25:06.051 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:06.052 ServerApp] 403 GET /api/kernelspecs?1713612305974 (@127.0.0.1) 1.94ms referer=None
[W 2024-04-20 12:25:06.052 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:06.053 ServerApp] 403 GET /api/kernels?1713612305975 (@127.0.0.1) 2.55ms referer=None
[W 2024-04-20 12:25:06.053 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:06.054 ServerApp] 403 GET /api/kernels?1713612305977 (@127.0.0.1) 3.16ms referer=None
[W 2024-04-20 12:25:06.054 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:06.054 ServerApp] 403 GET /api/sessions?1713612305978 (@127.0.0.1) 3.77ms referer=None
[W 2024-04-20 12:25:06.055 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:06.056 ServerApp] 403 GET /api/kernelspecs?1713612305980 (@127.0.0.1) 1.55ms referer=None
[W 2024-04-20 12:25:06.057 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:06.057 ServerApp] 403 GET /api/kernels?1713612305981 (@127.0.0.1) 2.25ms referer=None
[W 2024-04-20 12:25:06.165 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:06.166 ServerApp] 403 GET /api/kernelspecs?1713612306031 (@127.0.0.1) 1.31ms referer=None
[W 2024-04-20 12:25:06.167 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:06.167 ServerApp] 403 GET /api/kernels?1713612306032 (@127.0.0.1) 1.24ms referer=None
[W 2024-04-20 12:25:06.168 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:06.168 ServerApp] 403 GET /api/kernels?1713612306034 (@127.0.0.1) 1.78ms referer=None
[W 2024-04-20 12:25:06.168 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:06.169 ServerApp] 403 GET /api/sessions?1713612306034 (@127.0.0.1) 2.34ms referer=None
[W 2024-04-20 12:25:06.170 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:06.170 ServerApp] 403 GET /api/kernels?1713612306035 (@127.0.0.1) 1.05ms referer=None
[W 2024-04-20 12:25:06.170 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:06.171 ServerApp] 403 GET /api/sessions?1713612306036 (@127.0.0.1) 1.65ms referer=None
[W 2024-04-20 12:25:06.400 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:06.401 ServerApp] 403 GET /api/kernelspecs?1713612306165 (@127.0.0.1) 1.11ms referer=None
[W 2024-04-20 12:25:06.455 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.16ms referer=None
[W 2024-04-20 12:25:06.685 ServerApp] 404 GET /tree? (@127.0.0.1) 1.11ms referer=None
[W 2024-04-20 12:25:07.631 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:07.631 ServerApp] 403 GET /api/kernelspecs?1713612307539 (@127.0.0.1) 1.11ms referer=None
[W 2024-04-20 12:25:07.632 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:07.632 ServerApp] 403 GET /api/kernels?1713612307540 (@127.0.0.1) 0.81ms referer=None
[W 2024-04-20 12:25:07.732 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:07.732 ServerApp] 403 GET /api/kernels?1713612307630 (@127.0.0.1) 0.91ms referer=None
[W 2024-04-20 12:25:07.733 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:07.734 ServerApp] 403 GET /api/sessions?1713612307631 (@127.0.0.1) 0.66ms referer=None
[W 2024-04-20 12:25:08.020 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-20 12:25:08.021 ServerApp] 403 GET /api/kernelspecs?1713612307734 (@127.0.0.1) 1.18ms referer=None
[I 2024-04-20 12:26:30.678 ServerApp] User b67ac7d744e645b2bc34054a9601e216 logged in.
[I 2024-04-20 12:26:30.679 ServerApp] 302 POST /login? (b67ac7d744e645b2bc34054a9601e216@127.0.0.1) 102.75ms
[W 2024-04-21 10:01:05.417 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.31ms referer=None
[W 2024-04-21 10:01:05.579 ServerApp] 404 GET /hub/api (@127.0.0.1) 0.92ms referer=None
[W 2024-04-21 10:01:05.580 ServerApp] 404 GET /hub/api (@127.0.0.1) 0.86ms referer=None
[W 2024-04-21 10:01:05.581 ServerApp] 404 GET /hub/api (@127.0.0.1) 0.83ms referer=None
[W 2024-04-21 10:01:05.704 ServerApp] 404 GET /tree? (@127.0.0.1) 0.97ms referer=None
[W 2024-04-21 10:01:06.438 ServerApp] 404 GET /tree? (@127.0.0.1) 1.13ms referer=None
[W 2024-04-21 10:01:06.439 ServerApp] 404 GET /tree? (@127.0.0.1) 0.86ms referer=None
[W 2024-04-21 10:01:06.440 ServerApp] 404 GET /tree? (@127.0.0.1) 0.91ms referer=None
[W 2024-04-21 10:01:06.550 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:06.551 ServerApp] 403 GET /api/kernelspecs?1713690066485 (@127.0.0.1) 1.18ms referer=None
[W 2024-04-21 10:01:06.552 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:06.553 ServerApp] 403 GET /api/kernels?1713690066488 (@127.0.0.1) 1.35ms referer=None
[W 2024-04-21 10:01:06.553 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:06.553 ServerApp] 403 GET /api/kernelspecs?1713690066491 (@127.0.0.1) 1.93ms referer=None
[W 2024-04-21 10:01:06.554 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:06.555 ServerApp] 403 GET /api/kernels?1713690066492 (@127.0.0.1) 1.19ms referer=None
[W 2024-04-21 10:01:06.555 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:06.556 ServerApp] 403 GET /api/kernels?1713690066494 (@127.0.0.1) 1.79ms referer=None
[W 2024-04-21 10:01:06.557 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:06.557 ServerApp] 403 GET /api/sessions?1713690066496 (@127.0.0.1) 1.71ms referer=None
[W 2024-04-21 10:01:06.558 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:06.558 ServerApp] 403 GET /api/kernels?1713690066497 (@127.0.0.1) 2.26ms referer=None
[W 2024-04-21 10:01:06.558 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:06.559 ServerApp] 403 GET /api/sessions?1713690066498 (@127.0.0.1) 2.84ms referer=None
[W 2024-04-21 10:01:06.578 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:06.579 ServerApp] 403 GET /api/kernelspecs?1713690066556 (@127.0.0.1) 0.97ms referer=None
[W 2024-04-21 10:01:06.579 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:06.579 ServerApp] 403 GET /api/kernels?1713690066557 (@127.0.0.1) 0.63ms referer=None
[W 2024-04-21 10:01:06.590 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:06.591 ServerApp] 403 GET /api/kernels?1713690066578 (@127.0.0.1) 1.07ms referer=None
[W 2024-04-21 10:01:06.591 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:06.592 ServerApp] 403 GET /api/sessions?1713690066579 (@127.0.0.1) 0.86ms referer=None
[W 2024-04-21 10:01:06.623 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.02ms referer=None
[W 2024-04-21 10:01:06.624 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.39ms referer=None
[W 2024-04-21 10:01:06.624 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:06.625 ServerApp] 403 GET /api/kernelspecs?1713690066590 (@127.0.0.1) 0.71ms referer=None
[W 2024-04-21 10:01:06.665 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.09ms referer=None
[W 2024-04-21 10:01:06.711 ServerApp] 404 GET /tree? (@127.0.0.1) 1.24ms referer=None
[W 2024-04-21 10:01:06.712 ServerApp] 404 GET /tree? (@127.0.0.1) 1.21ms referer=None
[W 2024-04-21 10:01:06.713 ServerApp] 404 GET /tree? (@127.0.0.1) 1.64ms referer=None
[W 2024-04-21 10:01:07.106 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:07.107 ServerApp] 403 GET /api/kernelspecs?1713690066753 (@127.0.0.1) 1.18ms referer=None
[W 2024-04-21 10:01:07.107 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:07.108 ServerApp] 403 GET /api/kernels?1713690066754 (@127.0.0.1) 1.10ms referer=None
[W 2024-04-21 10:01:07.109 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:07.109 ServerApp] 403 GET /api/kernelspecs?1713690066755 (@127.0.0.1) 0.99ms referer=None
[W 2024-04-21 10:01:07.111 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:07.111 ServerApp] 403 GET /api/kernels?1713690066756 (@127.0.0.1) 1.88ms referer=None
[W 2024-04-21 10:01:07.111 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:07.112 ServerApp] 403 GET /api/kernels?1713690066758 (@127.0.0.1) 2.42ms referer=None
[W 2024-04-21 10:01:07.112 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:07.113 ServerApp] 403 GET /api/sessions?1713690066759 (@127.0.0.1) 2.97ms referer=None
[W 2024-04-21 10:01:07.113 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:07.114 ServerApp] 403 GET /api/kernels?1713690066760 (@127.0.0.1) 3.53ms referer=None
[W 2024-04-21 10:01:07.114 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:07.114 ServerApp] 403 GET /api/sessions?1713690066761 (@127.0.0.1) 4.03ms referer=None
[W 2024-04-21 10:01:07.187 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:07.188 ServerApp] 403 GET /api/kernelspecs?1713690066782 (@127.0.0.1) 1.13ms referer=None
[W 2024-04-21 10:01:07.188 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:07.189 ServerApp] 403 GET /api/kernels?1713690066784 (@127.0.0.1) 0.84ms referer=None
[W 2024-04-21 10:01:07.439 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:07.440 ServerApp] 403 GET /api/kernels?1713690067106 (@127.0.0.1) 1.12ms referer=None
[W 2024-04-21 10:01:07.441 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:07.441 ServerApp] 403 GET /api/sessions?1713690067107 (@127.0.0.1) 0.90ms referer=None
[W 2024-04-21 10:01:07.510 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:07.511 ServerApp] 403 GET /api/kernelspecs?1713690067186 (@127.0.0.1) 1.18ms referer=None
[W 2024-04-21 10:01:07.511 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:07.512 ServerApp] 403 GET /api/kernelspecs?1713690067190 (@127.0.0.1) 0.82ms referer=None
[W 2024-04-21 10:01:07.611 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:07.612 ServerApp] 403 GET /api/kernelspecs?1713690067439 (@127.0.0.1) 1.14ms referer=None
[W 2024-04-21 10:01:07.632 ServerApp] 404 GET /hub/api (@127.0.0.1) 0.99ms referer=None
[W 2024-04-21 10:01:07.679 ServerApp] 404 GET /tree? (@127.0.0.1) 1.06ms referer=None
[W 2024-04-21 10:01:07.708 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:07.709 ServerApp] 403 GET /api/kernelspecs?1713690067699 (@127.0.0.1) 1.11ms referer=None
[W 2024-04-21 10:01:07.710 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:07.710 ServerApp] 403 GET /api/kernels?1713690067700 (@127.0.0.1) 0.85ms referer=None
[W 2024-04-21 10:01:07.759 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:07.760 ServerApp] 403 GET /api/kernels?1713690067709 (@127.0.0.1) 1.11ms referer=None
[W 2024-04-21 10:01:07.760 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:07.761 ServerApp] 403 GET /api/sessions?1713690067711 (@127.0.0.1) 0.85ms referer=None
[W 2024-04-21 10:01:07.764 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 10:01:07.764 ServerApp] 403 GET /api/kernelspecs?1713690067758 (@127.0.0.1) 1.09ms referer=None
[I 2024-04-21 10:01:09.576 ServerApp] User 877944a9444646d3827b4464cee820ba logged in.
[I 2024-04-21 10:01:09.580 ServerApp] 302 POST /login? (877944a9444646d3827b4464cee820ba@127.0.0.1) 138.17ms
[I 2024-04-21 11:12:15.446 ServerApp] Creating new notebook in 
[I 2024-04-21 11:12:15.526 ServerApp] Saving Untitled.ipynb
[I 2024-04-21 11:12:17.932 ServerApp] Kernel started: f7e48b69-901c-4c6e-8df2-a6024e018a5b
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2024-04-21 11:12:18.623 ServerApp] Connecting to kernel f7e48b69-901c-4c6e-8df2-a6024e018a5b.
[I 2024-04-21 11:12:18.640 ServerApp] Connecting to kernel f7e48b69-901c-4c6e-8df2-a6024e018a5b.
[I 2024-04-21 11:12:18.663 ServerApp] Connecting to kernel f7e48b69-901c-4c6e-8df2-a6024e018a5b.
[I 2024-04-21 11:14:16.776 ServerApp] Saving file at /Untitled.ipynb
[I 2024-04-21 11:14:16.777 ServerApp] Saving Untitled.ipynb
[I 2024-04-21 11:16:17.219 ServerApp] Saving file at /Untitled.ipynb
[I 2024-04-21 11:16:17.220 ServerApp] Saving Untitled.ipynb
[I 2024-04-21 11:18:17.540 ServerApp] Saving file at /Untitled.ipynb
[I 2024-04-21 11:18:17.542 ServerApp] Saving Untitled.ipynb
[W 2024-04-21 13:51:59.404 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.20ms referer=None
[W 2024-04-21 13:51:59.680 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.11ms referer=None
[W 2024-04-21 13:51:59.680 ServerApp] 404 GET /hub/api (@127.0.0.1) 0.67ms referer=None
[W 2024-04-21 13:51:59.809 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.28ms referer=None
[W 2024-04-21 13:51:59.810 ServerApp] 404 GET /tree? (@127.0.0.1) 0.81ms referer=None
[W 2024-04-21 13:52:00.609 ServerApp] 404 GET /tree? (@127.0.0.1) 1.07ms referer=None
[W 2024-04-21 13:52:00.610 ServerApp] 404 GET /tree? (@127.0.0.1) 0.78ms referer=None
[W 2024-04-21 13:52:00.759 ServerApp] 404 GET /tree? (@127.0.0.1) 1.08ms referer=None
[W 2024-04-21 13:52:00.869 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:00.869 ServerApp] 403 GET /api/kernelspecs?1713703920751 (@127.0.0.1) 1.05ms referer=None
[W 2024-04-21 13:52:00.871 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:00.871 ServerApp] 403 GET /api/kernels?1713703920755 (@127.0.0.1) 1.60ms referer=None
[W 2024-04-21 13:52:00.872 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:00.872 ServerApp] 403 GET /api/kernels?1713703920759 (@127.0.0.1) 2.21ms referer=None
[W 2024-04-21 13:52:00.872 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:00.873 ServerApp] 403 GET /api/sessions?1713703920760 (@127.0.0.1) 2.87ms referer=None
[W 2024-04-21 13:52:00.873 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:00.874 ServerApp] 403 GET /api/kernelspecs?1713703920854 (@127.0.0.1) 3.51ms referer=None
[W 2024-04-21 13:52:00.874 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:00.875 ServerApp] 403 GET /api/kernels?1713703920855 (@127.0.0.1) 4.18ms referer=None
[W 2024-04-21 13:52:00.893 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:00.894 ServerApp] 403 GET /api/kernelspecs?1713703920845 (@127.0.0.1) 1.23ms referer=None
[W 2024-04-21 13:52:00.895 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:00.895 ServerApp] 403 GET /api/kernels?1713703920846 (@127.0.0.1) 1.13ms referer=None
[W 2024-04-21 13:52:00.895 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:00.896 ServerApp] 403 GET /api/kernels?1713703920848 (@127.0.0.1) 1.73ms referer=None
[W 2024-04-21 13:52:00.897 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:00.897 ServerApp] 403 GET /api/sessions?1713703920849 (@127.0.0.1) 1.18ms referer=None
[W 2024-04-21 13:52:00.898 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:00.898 ServerApp] 403 GET /api/kernels?1713703920870 (@127.0.0.1) 1.84ms referer=None
[W 2024-04-21 13:52:00.899 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:00.899 ServerApp] 403 GET /api/sessions?1713703920871 (@127.0.0.1) 1.07ms referer=None
[W 2024-04-21 13:52:00.933 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:00.934 ServerApp] 403 GET /api/kernelspecs?1713703920894 (@127.0.0.1) 1.16ms referer=None
[W 2024-04-21 13:52:00.972 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.09ms referer=None
[W 2024-04-21 13:52:00.973 ServerApp] 404 GET /hub/api (@127.0.0.1) 0.84ms referer=None
[W 2024-04-21 13:52:00.990 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.07ms referer=None
[W 2024-04-21 13:52:01.015 ServerApp] 404 GET /tree? (@127.0.0.1) 1.05ms referer=None
[W 2024-04-21 13:52:01.027 ServerApp] 404 GET /tree? (@127.0.0.1) 1.03ms referer=None
[W 2024-04-21 13:52:01.036 ServerApp] 404 GET /tree? (@127.0.0.1) 1.04ms referer=None
[W 2024-04-21 13:52:01.082 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:01.083 ServerApp] 403 GET /api/kernelspecs?1713703921032 (@127.0.0.1) 1.26ms referer=None
[W 2024-04-21 13:52:01.084 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:01.084 ServerApp] 403 GET /api/kernels?1713703921034 (@127.0.0.1) 1.18ms referer=None
[W 2024-04-21 13:52:01.085 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:01.085 ServerApp] 403 GET /api/kernels?1713703921035 (@127.0.0.1) 1.74ms referer=None
[W 2024-04-21 13:52:01.085 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:01.086 ServerApp] 403 GET /api/sessions?1713703921036 (@127.0.0.1) 2.32ms referer=None
[W 2024-04-21 13:52:01.152 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:01.152 ServerApp] 403 GET /api/kernelspecs?1713703921062 (@127.0.0.1) 1.23ms referer=None
[W 2024-04-21 13:52:01.153 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:01.154 ServerApp] 403 GET /api/kernels?1713703921063 (@127.0.0.1) 1.11ms referer=None
[W 2024-04-21 13:52:01.154 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:01.154 ServerApp] 403 GET /api/kernels?1713703921064 (@127.0.0.1) 1.66ms referer=None
[W 2024-04-21 13:52:01.155 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:01.156 ServerApp] 403 GET /api/sessions?1713703921065 (@127.0.0.1) 1.08ms referer=None
[W 2024-04-21 13:52:01.156 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:01.156 ServerApp] 403 GET /api/kernelspecs?1713703921068 (@127.0.0.1) 1.64ms referer=None
[W 2024-04-21 13:52:01.157 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:01.158 ServerApp] 403 GET /api/kernels?1713703921070 (@127.0.0.1) 0.95ms referer=None
[W 2024-04-21 13:52:01.163 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:01.164 ServerApp] 403 GET /api/kernels?1713703921082 (@127.0.0.1) 1.13ms referer=None
[W 2024-04-21 13:52:01.164 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:01.165 ServerApp] 403 GET /api/sessions?1713703921091 (@127.0.0.1) 0.84ms referer=None
[W 2024-04-21 13:52:01.823 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:01.824 ServerApp] 403 GET /api/kernelspecs?1713703921164 (@127.0.0.1) 1.10ms referer=None
[W 2024-04-21 13:52:02.102 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.03ms referer=None
[W 2024-04-21 13:52:02.210 ServerApp] 404 GET /tree? (@127.0.0.1) 0.97ms referer=None
[W 2024-04-21 13:52:03.289 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:03.290 ServerApp] 403 GET /api/kernelspecs?1713703923122 (@127.0.0.1) 1.11ms referer=None
[W 2024-04-21 13:52:03.291 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:03.291 ServerApp] 403 GET /api/kernels?1713703923123 (@127.0.0.1) 0.86ms referer=None
[W 2024-04-21 13:52:03.656 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:03.656 ServerApp] 403 GET /api/kernels?1713703923289 (@127.0.0.1) 1.20ms referer=None
[W 2024-04-21 13:52:03.657 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:03.658 ServerApp] 403 GET /api/sessions?1713703923290 (@127.0.0.1) 0.98ms referer=None
[W 2024-04-21 13:52:04.604 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/home/hass/base/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-04-21 13:52:04.604 ServerApp] 403 GET /api/kernelspecs?1713703923655 (@127.0.0.1) 1.09ms referer=None
[I 2024-04-21 13:52:05.535 ServerApp] User bc6c9476528540e3b3da81fcf0e140a6 logged in.
[I 2024-04-21 13:52:05.536 ServerApp] 302 POST /login? (bc6c9476528540e3b3da81fcf0e140a6@127.0.0.1) 106.42ms
